# -*- mode: ruby -*-
# vi: set ft=ruby :

$quagga = <<SCRIPT
  apt-get update -y
  apt-get install -y quagga traceroute

  # Enable IPv4 and IPv6 forwarding
  echo "net.ipv4.conf.all.forwarding=1" | sudo tee -a /etc/sysctl.conf
  echo "net.ipv4.conf.default.forwarding=1" | sudo tee -a /etc/sysctl.conf
  sed 's/#net.ipv6.conf.all.forwarding=1/net.ipv6.conf.all.forwarding=1/g' /etc/sysctl.conf | sudo tee /etc/sysctl.conf
  echo "net.ipv6.conf.default.forwarding=1" | sudo tee -a /etc/sysctl.conf
  sudo sysctl -p

  sed -i -e 's/zebra=no/zebra=yes/g' /etc/quagga/daemons
  sed -i -e 's/bgpd=no/bgpd=yes/g' /etc/quagga/daemons
SCRIPT

$router1 =  <<SCRIPT
cat > /etc/quagga/bgpd.conf << EOF
hostname quagga-int
log file /var/log/quagga/bgpd.log
log timestamp precision 6
!
password admin
enable password admin
!
router bgp 64496
 bgp router-id 192.168.2.242
 network 192.0.2.0/24
 neighbor 192.168.2.7 remote-as 64496
 neighbor 192.168.2.7 route-reflector-client
!
line vty
 exec-timeout 0 0
!
EOF

  service quagga restart
SCRIPT

$router2 =  <<SCRIPT
cat > /etc/quagga/bgpd.conf << EOF
hostname quagga-ext
log file /var/log/quagga/bgpd.log
log timestamp precision 6
!
password admin
enable password admin
!
router bgp 64497
 bgp router-id 192.168.2.243
 network 192.0.5.0/24
 neighbor 192.168.2.7 remote-as 64497
!
line vty
 exec-timeout 0 0
!
EOF

  service quagga restart
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--memory", "1024"]
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
  end
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"

  config.vm.define "quagga-int" do | h0 |
    # Provisioning
    h0.vm.hostname = "quagga-int"
    h0.vm.provision "shell", inline: $quagga
    h0.vm.provision "shell", inline: $router1
  end

  config.vm.define "quagga-ext" do | h1 |
    # Provisioning
    h1.vm.hostname = "quagga-ext"
    h1.vm.provision "shell", inline: $quagga
    h1.vm.provision "shell", inline: $router2
  end
end
