# -*- mode: ODL -*-

$init = <<SCRIPT
  apt-get update
  apt-get install -y autoconf automake gcc libtool libxml2 libxml2-dev m4 make cmake openssl libssl-dev pkg-config dbus dbus-*dev
  apt-get install -y linux-headers-$(uname -r) libxslt1-dev libssh2-1-dev libcurl4-openssl-dev xsltproc wget git python-setuptools g++
  apt-get clean && apt-get purge
SCRIPT

$ram_hugepage = <<SCRIPT
  sysctl -w vm.nr_hugepages=1024
  HUGEPAGES=`sysctl -n  vm.nr_hugepages`
  if [ $HUGEPAGES != 1024 ]; then
    echo "ERROR: Unable to get 1024 hugepages, only got $HUGEPAGES.  Cannot finish."
  exit
  fi
SCRIPT

$install_vpp_honeycamb = <<SCRIPT
  export UBUNTU="trusty"
  export RELEASE=".stable.1609"
  export VPP_VAGRANT_NICS=2
  sudo rm /etc/apt/sources.list.d/99fd.io.list
  echo "deb [trusted=yes] https://nexus.fd.io/content/repositories/fd.io$RELEASE.ubuntu.$UBUNTU.main/ ./" | sudo tee -a /etc/apt/sources.list.d/99fd.io.list
  sudo apt-get update
  sudo apt-get install -y vpp vpp-lib vpp-dpdk-dkms vpp-plugins vpp-nsh-plugin honeycomb
SCRIPT

$install_java = <<SCRIPT
  sudo apt-get install software-properties-common -y
  sudo add-apt-repository ppa:openjdk-r/ppa -y
  sudo apt-get update
  sudo apt-get install openjdk-8-jdk -y
  sudo update-java-alternatives --set java-1.8.0-openjdk-amd64
  export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\$JAVA_HOME/bin
SCRIPT

$install_docker = <<SCRIPT
  sudo apt-get update
  sudo apt-get install apt-transport-https ca-certificates -y
  sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
  sudo apt-get update
  apt-cache policy docker-engine
  sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual -y
  sudo apt-get update
  sudo apt-get install docker-engine -y --force-yes
  sudo curl -L "https://github.com/docker/compose/releases/download/1.9.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
  docker-compose --version
SCRIPT

$cleanup = <<SCRIPT
  apt-get clean && apt-get purge
  rm -rf /tmp/*
SCRIPT


Vagrant.configure("2") do |config|

config.vm.define "vpp1", autostart: true do |vpp1|

  vpp1.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  vpp1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      v.customize ["modifyvm", :id, "--memory", "4024"]
      #support for the SSE4.x instruction is required in some versions of VB.
      v.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
      v.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
  end

  ## Guest config change the network interface "en0" based on your PC configuration
  vpp1.vm.hostname = "VPP-vm1"
  vpp1.vm.network :public_network, bridge: "en0: Ethernet"
  vpp1.vm.network "private_network", type: "dhcp"

  ## Provisioning
  vpp1.vm.provision :shell, :inline => $ram_hugepage
  vpp1.vm.provision :shell, :inline => $init
  vpp1.vm.provision :shell, privileged: false, :inline => $install_java
  vpp1.vm.provision :shell, privileged: false, :inline => $install_vpp_honeycamb
  vpp1.vm.provision :shell, privileged: false, :inline => $install_docker
  vpp1.vm.provision :shell, :inline => $cleanup

  ## SSH config
  vpp1.ssh.forward_x11 = false
end

config.vm.define "vpp2", autostart: true do |vpp2|

  vpp2.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

  vpp2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      v.customize ["modifyvm", :id, "--memory", "4024"]
      #support for the SSE4.x instruction is required in some versions of VB.
      v.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.1", "1"]
      v.customize ["setextradata", :id, "VBoxInternal/CPUM/SSE4.2", "1"]
  end

  ## Guest config change the network interface "en0" based on your PC configuration
  vpp2.vm.hostname = "VPP-vm2"
  vpp2.vm.network :public_network, bridge: "en0: Ethernet"
  vpp2.vm.network "private_network", type: "dhcp"

  ## Provisioning
  vpp2.vm.provision :shell, :inline => $ram_hugepage
  vpp2.vm.provision :shell, :inline => $init
  vpp2.vm.provision :shell, privileged: false, :inline => $install_java
  vpp2.vm.provision :shell, privileged: false, :inline => $install_vpp_honeycamb
  vpp2.vm.provision :shell, privileged: false, :inline => $install_docker
  vpp2.vm.provision :shell, :inline => $cleanup

  ## SSH config
  vpp2.ssh.forward_x11 = false
end
end